# Generated by Django 4.1.7 on 2023-02-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(choices=[('COMPUTO', 'COMPUTO'), ('HOGAR', 'HOGAR'), ('ENTRETENIMIENTO', 'ENTRETENIMIENTO'), ('PRODUCTOS BELLEZA', 'PRODUCTOS BELLEZA')], max_length=90)),
                ('categoria_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.TextField(blank=True, null=True)),
                ('producto_imagen', models.CharField(blank=True, max_length=120, null=True)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('producto_estado', models.BooleanField(default=True)),
                ('producto_stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
    ]
