# Generated by Django 4.1.7 on 2023-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=90)),
                ('proveedor_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categorias',
            name='categoria_nombre',
            field=models.CharField(choices=[('COMPUTO', 'COMPUTO'), ('HOGAR', 'HOGAR'), ('ENTRETENIMIENTO', 'ENTRETENIMIENTO'), ('PRODUCTOS BELLEZA', 'PRODUCTOS BELLEZA'), ('JARDINERIA', 'JARDINERIA')], max_length=90),
        ),
    ]
