# Generated by Django 4.1.7 on 2023-02-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proveedor_alter_categorias_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
    ]
